config/routes.rb
Rails.application.routes.draw do
  resources :items do
    post 'mark_as_completed', on: :member
  end

  resources :item_types, only: [:index, :show] do
    resources :items
  end

  root 'item_types#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_type
  validates :title, presence: true, length: {minimum: 2}

  def completed?
    !completed_on.nil?
  end

  def fetch_image
    update_attribute(:image_url, ImageFetcher.new.fetch(title))
  end

  def mark_as_completed
    update_attribute(:completed_on, Date.today)
  end
end

app/models/item_type.rb
class ItemType < ActiveRecord::Base
  has_many :items
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/item_types_controller.rb
class ItemTypesController < ApplicationController
  def index
    @item_types = ItemType.all
  end

  def show
    @item_type = ItemType.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :lookup_item_type
before_action :lookup_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def new
    @item = @item_type.items.new
  end

  def show
    #@item = @item_type.items.find(params[:id])
  end

  def create
    @item = @item_type.items.new(item_params)

    if @item.save
      @item.fetch_image
      redirect_to root_path, notice: "Success! We Added your thing!"
    else
      render :new
    end
  end

  def edit
    #@item = Item.find(params[:id])
  end

  def update
    #@item = Item.find(params[:id])

    if @item.update_attributes(item_params)
      @item.fetch_image
      redirect_to root_path, notice: "Success! We Edited your thing!"
    else
      render :edit
    end
  end

  def destroy
    #@item = Item.find(params[:id])
    @item.destroy
    redirect_to root_path, notice: "Poof!"
  end

  def mark_as_completed
    @item = Item.find(params[:id])
    @item.mark_as_completed
    redirect_to root_path
  end
  
  private

  def item_params
    params.require(:item).permit(:title, :completed_on, :item_type_id)
  end

  def lookup_item_type
    @item_type = ItemType.find(params[:item_type_id])
  end

  def lookup_item
    @item = @item_type.items.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_types_helper.rb
module ItemTypesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/item_types/index.html.erb
<h1>Select an Item Type</h1>

<% @item_types.each do |item_type| %>
  <h3><%= item_type.name %></h3>

  <p><%= link_to 'Add a new one', new_item_type_item_path(item_type) %></p>

  <% item_type.items.each do |item| %>
    <p><%= link_to item.title, item_type_item_path(item_type, item) %></p>
  <% end %>
<% end %>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <div class='errors'>
    <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>  
    </ul>
  </div>

  <div class='field'>
    <%= f.label :title, 'What is the title?' %>
    <%= f.text_field :title %>
  </div>
  
  <div class='field'>
    <%= f.label :item_type_id, 'What type of item is this?' %>
    <%= f.collection_select :item_type_id, ItemType.all, :id, :name, prompt: true %>
  </div>

  <div class='field'>
    <%= f.label :completed_on, 'When was it read/watched?' %>
    <%= f.date_select :completed_on, start_year: 1990, :include_blank => true, :default => nil %>
  </div>
  
  <div class='field'>
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<h1>Items</h1>

<br>
<p><%= link_to 'New Item', new_item_path %></p>
<br>

<table>
  <tr>
    <th>Title</th>
    <th>Type</th>
    <th>Image</th>
    <th>Completed</th>
    <th>Edit</th>
    <th>Delete</th>
    <th>Mark as Completed</th>
  </tr>
<% @items.each do |item| %>
  <tr>
    <td><%= item.title %></td>
    <td class='center'><%= item.item_type.name %></td>
    <td class='center'><%= image_tag(item.image_url) if !item.image_url.nil? %></td>
    <td class='center'><%= 'Yes' if item.completed? %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Delete', item_path(item), method: :delete %></td>
    <td><%= link_to_if(!item.completed?, 'Mark as completed', mark_as_completed_item_path(item), method: :mark_as_completed){} %></td>
  </tr>  
<% end %>

</table>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<h1>The Item Type is <%= @item_type.name %></h1>

<h2>This Item: <%= @item.title %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <h1>My Library App</h1>
</header>

<% flash.each do |key, msg| %>
  <p class="flash-<%= key %>"><%= msg %></p>
<% end %>

<%= yield %>

<footer>
  <small>Created by me - 2015</small>
</footer>

</body>
</html>